// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLVbN4-MCsSfftMVa12xEcJuz2APxPtRI',
    appId: '1:1014039058787:web:3d4eb0018b4731de999b56',
    messagingSenderId: '1014039058787',
    projectId: 'delicia1-e5f4e',
    authDomain: 'delicia1-e5f4e.firebaseapp.com',
    storageBucket: 'delicia1-e5f4e.firebasestorage.app',
    measurementId: 'G-V77KGLSZD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA86O3z2vob5EimKlsV9QXDMWgldSiIAsU',
    appId: '1:1014039058787:android:01b407abb8e60ea4999b56',
    messagingSenderId: '1014039058787',
    projectId: 'delicia1-e5f4e',
    storageBucket: 'delicia1-e5f4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9rpoBXe2r2wL1-nttc8SAC1PNxXgUk7g',
    appId: '1:1014039058787:ios:860f844f7dfaac81999b56',
    messagingSenderId: '1014039058787',
    projectId: 'delicia1-e5f4e',
    storageBucket: 'delicia1-e5f4e.firebasestorage.app',
    iosBundleId: 'com.example.delicia1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9rpoBXe2r2wL1-nttc8SAC1PNxXgUk7g',
    appId: '1:1014039058787:ios:860f844f7dfaac81999b56',
    messagingSenderId: '1014039058787',
    projectId: 'delicia1-e5f4e',
    storageBucket: 'delicia1-e5f4e.firebasestorage.app',
    iosBundleId: 'com.example.delicia1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLVbN4-MCsSfftMVa12xEcJuz2APxPtRI',
    appId: '1:1014039058787:web:d7e8b81b1dccad91999b56',
    messagingSenderId: '1014039058787',
    projectId: 'delicia1-e5f4e',
    authDomain: 'delicia1-e5f4e.firebaseapp.com',
    storageBucket: 'delicia1-e5f4e.firebasestorage.app',
    measurementId: 'G-2KESPX52ML',
  );
}
